### PR TITLE
⭐️ Add ansible-lint github action

### PR DESCRIPTION
**Pull request by tas50**
Signed-off-by: Tim Smith <tsmith@mondoo.com>

### CODE REVIEW

**Comment by chris-rock** [comment]
This is a great addition @tas50 Could we also include a make task so that we can run the same tests locally without triggering the GitHub action?

**Comment by chris-rock** [comment]
rebased on top of #13 to get it green

**Comment by tas50** [comment]
@chris-rock not sure if you want to tackle that permissions issue or disable that rule.

**Comment by chris-rock** [comment]
@tas50 We tackle that in further iterations. That requires some additional testing.

**Pull request merged**
